export type Theme = {
  background: string;
  surface: string;
  surfaceRaised: string;
  accent: string;
  accentLight: string;
  accentText: string;
  fabBg: string;
  fabIcon: string;
  headerTitle: string;
  headerSubtitle: string;
  dateInactiveBg: string;
  dateActiveBg: string;
  dateInactiveText: string;
  dateActiveText: string;
  cardDefault: string;
  cardFamily: string;
  cardHealth: string;
  cardLearning: string;
  cardSelfCare: string;
  cardTitle: string;
  cardTime: string;
  cardDuration: string;
  badgeFamilyBg: string;
  badgeFamilyText: string;
  badgeHealthBg: string;
  badgeHealthText: string;
  badgeLearningBg: string;
  badgeLearningText: string;
  badgeSelfCareBg: string;
  badgeSelfCareText: string;
  checkboxBorder: string;
  checkboxCheckedBg: string;
  checkboxTick: string;
  tabBarBg: string;
  tabIconActive: string;
  tabIconInactive: string;
  text: string;
  textMuted: string;
  border: string;
};

export const themes = {
  light: {
    background: "#f9e3fc",
    surface: "white",
    surfaceRaised: "white",
    accent: "#6C47FF",
    accentLight: "#EAE4FF",
    accentText: "white",
    fabBg: "#FF5A5F",
    fabIcon: "white",
    headerTitle: "#1A1635",
    headerSubtitle: "#8A8A9A",
    dateInactiveBg: "#EAE4FF",
    dateActiveBg: "#6C47FF",
    dateInactiveText: "#8A8A9A",
    dateActiveText: "white",
    cardDefault: "white",
    cardFamily: "#F0EDFF",
    cardHealth: "#E8F5F0",
    cardLearning: "#FFF4EC",
    cardSelfCare: "#EFF6FF",
    cardTitle: "#1A1635",
    cardTime: "#5A5870",
    cardDuration: "#8A8A9A",
    badgeFamilyBg: "#DDD6FE",
    badgeFamilyText: "#4C1D95",
    badgeHealthBg: "#A7F3D0",
    badgeHealthText: "#065F46",
    badgeLearningBg: "#FED7AA",
    badgeLearningText: "#92400E",
    badgeSelfCareBg: "#BFDBFE",
    badgeSelfCareText: "#1E40AF",
    checkboxBorder: "#D1D1DF",
    checkboxCheckedBg: "#1A1635",
    checkboxTick: "white",
    tabBarBg: "white",
    tabIconActive: "#6C47FF",
    tabIconInactive: "#C4C2D4",
    text: "#1A1635",
    textMuted: "#8A8A9A",
    border: "#EDEAF8",
  },
  dark: {
    background: "#12111F",
    surface: "#1E1C30",
    surfaceRaised: "#1E1C30",
    accent: "#7C5CFF",
    accentLight: "#2A2448",
    accentText: "white",
    fabBg: "#FF5A5F",
    fabIcon: "white",
    headerTitle: "white",
    headerSubtitle: "#6B6A80",
    dateInactiveBg: "#2A2448",
    dateActiveBg: "#7C5CFF",
    dateInactiveText: "#6B6A80",
    dateActiveText: "white",
    cardDefault: "#1E1C30",
    cardFamily: "#221E3A",
    cardHealth: "#172A24",
    cardLearning: "#2A1F12",
    cardSelfCare: "#162030",
    cardTitle: "#F0EFFA",
    cardTime: "#9896AC",
    cardDuration: "#6B6A80",
    badgeFamilyBg: "#3D3560",
    badgeFamilyText: "#C4B5FD",
    badgeHealthBg: "#134E38",
    badgeHealthText: "#6EE7B7",
    badgeLearningBg: "#3D2A0A",
    badgeLearningText: "#FCD34D",
    badgeSelfCareBg: "#0C2240",
    badgeSelfCareText: "#93C5FD",
    checkboxBorder: "#3A384E",
    checkboxCheckedBg: "#7C5CFF",
    checkboxTick: "white",
    tabBarBg: "#1E1C30",
    tabIconActive: "#7C5CFF",
    tabIconInactive: "#3D3C52",
    text: "#F0EFFA",
    textMuted: "#6B6A80",
    border: "#2A2840",
  },
};

export type ThemeName = keyof typeof themes;
