export type Theme = {
  background: string;
  surface: string;
  surfaceRaised: string;
  accent: string;
  accentLight: string;
  accentText: string;
  fabBg: string;
  fabIcon: string;
  headerTitle: string;
  headerSubtitle: string;
  dateInactiveBg: string;
  dateActiveBg: string;
  dateInactiveText: string;
  dateActiveText: string;
  cardDefault: string;
  cardFamily: string;
  cardHealth: string;
  cardLearning: string;
  cardSelfCare: string;
  cardTitle: string;
  cardTime: string;
  cardDuration: string;
  badgeFamilyBg: string;
  badgeFamilyText: string;
  badgeHealthBg: string;
  badgeHealthText: string;
  badgeLearningBg: string;
  badgeLearningText: string;
  badgeSelfCareBg: string;
  badgeSelfCareText: string;
  checkboxBorder: string;
  checkboxCheckedBg: string;
  checkboxTick: string;
  tabBarBg: string;
  tabIconActive: string;
  tabIconInactive: string;
  text: string;
  textMuted: string;
  border: string;
};

export const themes = {
  light: {
    background: "bg-[#F8F7FF]",
    surface: "bg-white",
    surfaceRaised: "bg-white",
    accent: "bg-[#6C47FF]",
    accentLight: "bg-[#EAE4FF]",
    accentText: "text-white",
    fabBg: "bg-[#FF5A5F]",
    fabIcon: "text-white",
    headerTitle: "text-[#1A1635]",
    headerSubtitle: "text-[#8A8A9A]",
    dateInactiveBg: "bg-[#EAE4FF]",
    dateActiveBg: "bg-[#6C47FF]",
    dateInactiveText: "text-[#8A8A9A]",
    dateActiveText: "text-white",
    cardDefault: "bg-white",
    cardFamily: "bg-[#F0EDFF]",
    cardHealth: "bg-[#E8F5F0]",
    cardLearning: "bg-[#FFF4EC]",
    cardSelfCare: "bg-[#EFF6FF]",
    cardTitle: "text-[#1A1635]",
    cardTime: "text-[#5A5870]",
    cardDuration: "text-[#8A8A9A]",
    badgeFamilyBg: "bg-[#DDD6FE]",
    badgeFamilyText: "text-[#4C1D95]",
    badgeHealthBg: "bg-[#A7F3D0]",
    badgeHealthText: "text-[#065F46]",
    badgeLearningBg: "bg-[#FED7AA]",
    badgeLearningText: "text-[#92400E]",
    badgeSelfCareBg: "bg-[#BFDBFE]",
    badgeSelfCareText: "text-[#1E40AF]",
    checkboxBorder: "border-[#D1D1DF]",
    checkboxCheckedBg: "bg-[#1A1635]",
    checkboxTick: "text-white",
    tabBarBg: "bg-white",
    tabIconActive: "#6C47FF",
    tabIconInactive: "#C4C2D4",
    text: "text-[#1A1635]",
    textMuted: "text-[#8A8A9A]",
    border: "border-[#EDEAF8]",
  },
  dark: {
    background: "bg-[#12111F]",
    surface: "bg-[#1E1C30]",
    surfaceRaised: "bg-[#1E1C30]",
    accent: "bg-[#7C5CFF]",
    accentLight: "bg-[#2A2448]",
    accentText: "text-white",
    fabBg: "bg-[#FF5A5F]",
    fabIcon: "text-white",
    headerTitle: "text-[#F0EFFA]",
    headerSubtitle: "text-[#6B6A80]",
    dateInactiveBg: "bg-[#2A2448]",
    dateActiveBg: "bg-[#7C5CFF]",
    dateInactiveText: "text-[#6B6A80]",
    dateActiveText: "text-white",
    cardDefault: "bg-[#1E1C30]",
    cardFamily: "bg-[#221E3A]",
    cardHealth: "bg-[#172A24]",
    cardLearning: "bg-[#2A1F12]",
    cardSelfCare: "bg-[#162030]",
    cardTitle: "text-[#F0EFFA]",
    cardTime: "text-[#9896AC]",
    cardDuration: "text-[#6B6A80]",
    badgeFamilyBg: "bg-[#3D3560]",
    badgeFamilyText: "text-[#C4B5FD]",
    badgeHealthBg: "bg-[#134E38]",
    badgeHealthText: "text-[#6EE7B7]",
    badgeLearningBg: "bg-[#3D2A0A]",
    badgeLearningText: "text-[#FCD34D]",
    badgeSelfCareBg: "bg-[#0C2240]",
    badgeSelfCareText: "text-[#93C5FD]",
    checkboxBorder: "border-[#3A384E]",
    checkboxCheckedBg: "bg-[#7C5CFF]",
    checkboxTick: "text-white",
    tabBarBg: "bg-[#1E1C30]",
    tabIconActive: "#7C5CFF",
    tabIconInactive: "#3D3C52",
    text: "text-[#F0EFFA]",
    textMuted: "text-[#6B6A80]",
    border: "border-[#2A2840]",
  },
};

export type ThemeName = keyof typeof themes;
