import { Task } from "../types/types";

export const sampleTasks: Task[] = [
  {
    id: 1,
    title: "Lunch with Mom",
    createdAt: new Date(),
    postponedTo: null,
    emoji: "🍲",
    color: "#ECE4D7",
    duration: 30,
    timeSlot: "13:30 - 14:00",
    Categories: ["Family", "Health"],
    Reminders: ["30 minutes before"],
    isCompleted: false,
  },
  {
    id: 2,
    title: "Evening Workout",
    createdAt: new Date(),
    postponedTo: null,
    emoji: "🏋️‍♂️",
    color: "#EBCBF4",
    duration: 60,
    timeSlot: "18:00 - 19:00",
    Categories: ["Health", "Fitness"],
    Reminders: ["1 hour before", "15 minutes before"],
    isCompleted: true,
  },
  {
    id: 3,
    title: "Read a Book",
    createdAt: new Date(),
    postponedTo: null,
    emoji: "📚",
    color: "#E1F9BB",
    duration: 45,
    timeSlot: "20:00 - 20:45",
    Categories: ["Education", "Reading"],
    Reminders: ["30 minutes before"],
    isCompleted: false,
  },
  {
    id: 4,
    title: "Coffee Break & Relax",
    createdAt: new Date(),
    postponedTo: null,
    emoji: "☕",
    color: "#9ED0E6",
    duration: 15,
    timeSlot: "10:00 - 10:15",
    Categories: ["Breaks", "Self-care"],
    Reminders: ["5 minutes before"],
    isCompleted: false,
  },
  {
    id: 5,
    title: "Dinner with Sarah",
    createdAt: new Date("2024-06-01T19:00:00"),
    postponedTo: null,
    emoji: "🍽️",
    color: "#F9C5D1",
    duration: 90,
    timeSlot: "19:00 - 20:30",
    Categories: ["Social", "Food"],
    Reminders: ["1 hour before", "15 minutes before"],
    isCompleted: false,
  },
];
